global:
  smtp_from: 'example@gmail.com'
  smtp_smarthost: smtp.gmail.com:587
  smtp_auth_username: 'example@gmail.com'
  smtp_auth_identity: 'example@gmail.com'
  smtp_auth_password: 'fqkvkumorgaqgkat'
  pagerduty_url: #Your url

route:
  # fallback receiver
  receiver: admin
  group_wait: 2m
  group_interval: 10s
  repeat_interval: 1m
  routes:
    # Star Solutions.
  - match_re:
      app_type: (linux|windows)
    # fallback receiver 
    receiver: ss-admin
    # group_by: [severity]
    routes:
    # Linux team
    - match:
        app_type: linux
      # fallback receiver
      receiver: linux-teamlead
      routes:
      - match:
          severity: critical
        receiver: delivery-manager
        continue: true # Routing process will continue and not stop once routing is matched
      - match:
          severity: warning
        receiver: linux-teamlead

    # Windows team
    - match:
        app_type: windows
      # group_by: [severity]
      # fallback receiver
      receiver: windows-teamlead
      routes:
      - match:
          severity: critical
        receiver: delivery-manager
      - match:
          severity: warning
        receiver: windows-teamlead

    # PEC Technologies.
  - match_re:
      app_type: (python|go)
    # fallback receiver 
    receiver: pec-admin
    routes:
    # Python team
    - match:
        app_type: python
      # fallback receiver
      receiver: python-team-admin
      routes:
      - match:
          severity: critical
        receiver: python-team-manager
      - match:
          severity: warning
        receiver: python-team-lead

    # Go team
    - match:
        app_type: go
      # fallback receiver
      receiver: go-team-admin
      routes:
      - match:
          severity: critical
        receiver: go-team-manager
      - match:
          severity: warning
        receiver: go-team-lead
        
inhibit_rules:
- source_match:
    severity: 'critical'
    # which alert should be in the firing state
  target_match:
    severity: 'warning'
    # if the source_match alert is fired then which alert should be inhibitted
  equal: ['app_type', 'category']

receivers:
- name: admin
  email_configs:
  - to: 'example@gmail.com'

- name: ss-admin
  email_configs:
  - to: 'example@gmail.com'

- name: linux-team-admin
  email_configs:
  - to: 'example@gmail.com'

- name: linux-team-lead
  email_configs:
  - to: 'example@gmail.com'

- name: linux-team-manager
  pagerduty_configs:
  - service_key: # Your Service Key

- name: windows-team-admin
  email_configs:
  - to: 'example@gmail.com'

- name: windows-team-lead
  email_configs:
  - to: 'example@gmail.com'

# Adding Slack Integration
- name: windows-team-manager
  slack_configs:
  - channel: '#prometheus'
    api_url: 'https://hooks.slack.com/services/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'
    title: 'WMI exporter is down'
    text: 'WMI exporter is down for 2 minutes'

- name: pec-admin
  email_configs:
  - to: 'example@gmail.com'

- name: python-team-admin
  email_configs:
  - to: 'example@gmail.com'

- name: python-team-lead
  email_configs:
  - to: 'example@gmail.com'

- name: python-team-manager
  email_configs:
  - to: 'example@gmail.com'

- name: go-team-admin
  email_configs:
  - to: 'example@gmail.com'

- name: go-team-lead
  email_configs:
  - to: 'example@gmail.com'

- name: go-team-manager
  email_configs:
  - to: 'example@gmail.com'